### ISSUE TITLE
can`t read the property trim of 'undefind

### ISSUE THREAD

**Issue by srinivas1918** [benjaminws/stomp-js#42]
D:\snalla\nodejsexp\mqExp\node_modules\stomp\lib\stomp.js:54
        headers[header[0].trim()] = header[1].trim()                                    ^
TypeError: Cannot read property 'trim' of undefined
    at parse_headers (D:\snalla\nodejsexp\mqExp\node_modules\stomp\lib\stomp.js:
54:46)
    at parse_frame (D:\snalla\nodejsexp\mqExp\node_modules\stomp\lib\stomp.js:76
:15)
    at Socket.<anonymous> (D:\snalla\nodejsexp\mqExp\node_modules\stomp\lib\stom
p.js:160:28)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

**Comment by QAnders** [comment]
+1

**Comment by QAnders** [comment]
Ok, I got rid of this... The server is requiring SSL (TLS) so when I added SSL it started working.
The error is not very describing though... :)

I would, thus, interpret this error as "connections failed"...
